config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :logs
  root to: 'logs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord

  include PgSearch
  pg_search_scope :search_by_title_and_body, :against => [:title],
    using: {
      :tsearch => {:prefix => true}
    }



  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :log

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/log_controller.rb
class LogController < ApplicationController
before_action :authenticate_user!, #:except => [ :show]
def index
    @logs = current_user.logs
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  def show
    @log = Log.find(params[:id])

    p @log
    respond_to do |format|
      format.html
      format.json { render json: @log }
    end
  end

  def new
    @log = Log.new
  end

  def edit
    @log = Log.find(params[:id])
  end

  def create
    @log = Log.new(log_params)
    @user = current_user
    uploaded_file = params[:log][:picture].path
    p params
    p uploaded_file
    cloudinary_file = Cloudinary::Uploader.upload(uploaded_file, :folder => "journal-on-rails")
    p cloudinary_file
    p cloudinary_file["public_id"]
    #store this public_id value to the database
    @log.attributes = {:image => cloudinary_file["public_id"]}
    @log.attributes = {:user_id => current_user.id}


    # render json: cloudinary_file
    # @song["public_id"] = cloudinary_file["public_id"]
    p @log
    if @log.save
      redirect_to @log
      #ExampleMailer.sample_email(@user).deliver_now
    else
      render 'new'
    end
  end

  def update
    @log = Log.find(params[:id])

    if params[:log][:picture]
      uploaded_file = params[:log][:picture].path
      p uploaded_file
      cloudinary_file = Cloudinary::Uploader.upload(uploaded_file, :folder => "journal-on-rails")

      p cloudinary_file
      p cloudinary_file["url"]

      @log.attributes = {:image => cloudinary_file["public_id"]}
    else
      log_params[:image] = @log.image
    end

    if @log.update(log_params)
      redirect_to @log
    else
      render 'logs/edit'
    end
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path
  end

  private
    def log_params
      params.require(:log).permit(:title, :content, :image) #
    end

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
before_action :authenticate_user!, #:except => [ :show]

  def index
    if params[:search]
      @search_results_logs = Log.search_by_title_and_body(params[:search])
      respond_to do |format|
        format.js {render partial: 'search-results'}
      end
    else
      @logs = Log.where(:user_id => current_user.id).order('created_at DESC')
      @name = current_user.name

      #@logs = current_user.logs
      respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
      end
    end
  end

  def show
    @log = Log.find(params[:id])

    p @log
    respond_to do |format|
      format.html
      format.json { render json: @log }
    end
    p ENV['CLOUDINARY_URL']
  end

  def new
    if log_params
      #If data submitted already by the form we call the create method
      create
      return
    end

    @log = Log.new
    render 'new'  #calling the newly created log explicitly
  end

  def edit
    @log = Log.find(params[:id])
  end

  def create
    @log = Log.new(log_params)
    @user = current_user

    if !params[:log][:picture]
      #if no image uploaded, upload an empty string

      @log.attributes = {:image => " "}
      @log.attributes = {:user_id => current_user.id}

    else
      #else we upload the path of the image from cloudinary
      p 'uploaded file path here below:'
      uploaded_file = params[:log][:picture].path
      p "params here below:"
      p params
      p "uploaded file below:"
      p uploaded_file
      cloudinary_file = Cloudinary::Uploader.upload(uploaded_file, :folder => "journal-on-rails")
      p "cloudinary file:"
      p cloudinary_file
      p "cloudinary_file public id:"
      p cloudinary_file["public_id"]
      #store this public_id value to the database
      @log.attributes = {:image => cloudinary_file["public_id"]}
      @log.attributes = {:user_id => current_user.id}

    end

    # render json: cloudinary_file
    # @song["public_id"] = cloudinary_file["public_id"]
    p @log
    respond_to do |format|
      if @log.save
        #redirect_to @log
        format.html { redirect_to @log, notice: "Entry created!" }
        p "Log saved!"
        #ExampleMailer.sample_email(@user).deliver_now
      else
        #render 'new'
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @log = Log.find(params[:id])

    if params[:log][:picture]
      p "begin cloudinary upload if there is image: "
      uploaded_file = params[:log][:picture].path
      p "printing uploaded_file path below: "
      p uploaded_file
      cloudinary_file = Cloudinary::Uploader.upload(uploaded_file, :folder => "journal-on-rails")

      p "printing cloudinary_file below: "
      p cloudinary_file

      p "printing cloudinary_file url below: "
      p cloudinary_file["url"]


      @log.attributes = {:image => cloudinary_file["public_id"]}
    else
      log_params[:image] = @log.image
    end

# respond_to do |format|
#       if @log.save
#         #redirect_to @log
#         format.html { redirect_to @log, notice: "Entry created!" }
#         p "Log updated!"
#         #ExampleMailer.sample_email(@user).deliver_now
#       else
#         #render 'new'
#         format.html { render action: 'new' }
#       end
#     end

    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to @log, notice: "Entry updated!" }
        p "Log updated!"
      else
        format.html { render action: 'logs/edit' }
      end
    end
  end

  def destroy
    @log = Log.find(params[:id])
    @log.destroy
    redirect_to logs_path
  end

  private

    def log_params
      if params[:log].nil? || params[:log].empty?
        return false
      else
        return params.require(:log).permit(:title, :content, :image)
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalOnRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
		<nav class="navbar navbar-inverse">
  		<div class="container">
   	 		<div class="navbar-header">
      		<%= link_to 'Agenda', root_path, class: 'navbar-brand' %>
    		</div>
    	<div id="navbar">
      	<ul class="nav navbar-nav">
        	<li><%= link_to 'Home', root_path %></li>
      	</ul>
      	<ul class="nav navbar-nav pull-right">
        	<% if user_signed_in? %>
          	<li class="dropdown">
            	<a class="dropdown-toggle" data-toggle="dropdown" href="#">
              	<%= current_user.name %>
              		<span class="caret"></span>
            	</a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          	</li>
        	<% else %>
          	<li><%= link_to 'Log In', new_user_session_path %></li>
          	<li><%= link_to 'Sign Up', new_user_registration_path %></li>
        	<% end %>
      	</ul>
    	</div>
  		</div>

		</nav>

    <!--<p class="notice"><%= notice %></p> -->
    <!--<p class="alert"><%= alert %></p> -->
    <div class="container">
  		<% flash.each do |key, value| %>
    		<div class="alert alert-<%= key %>">
      		<%= value %>
    		</div>
  		<% end %>
		</div>

		<%= yield :top_content %>

		<div class="container">
    	<h1><%= yield :header %></h1>
  		<%= yield %>
		</div>
  </body>
</html>

app/views/logs/_results.html.erb
	<table class="table table-striped">
		<%= link_to 'Show All', logs_path %>
					<thead>
						<tr>
							<th scope="col">Title</th>
							<th scope="col">Created On</th>
							<th scope="col">Thumb Nails</th>
						</tr>
					</thead>
				<tbody>
					<% @search_results_logs.each do |log| %>
						<tr>
							<td class = "log-title"><%= log.title %></td>
							<td><%= log.created_at.strftime('%d.%m.%Y') %></td>
							<td> <%= cl_image_tag(log.image, :width => 50, :fetch_format=>:auto, :crop=>"scale")%></td>
							<td>
								<%= link_to 'Show', log_path(log)%>
							</td>
							<td>
								<%= link_to 'Edit', edit_log_path(log)%>
							</td>
							<td>
								<%= link_to 'Delete', log_path(log),
								method: :delete,
								data: { confirm: 'Are you really sure you want to delete this entry??' } %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>

app/views/logs/_search-results.js.erb
$("#log-table").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/logs/edit.html.erb
<h4>Edit Log</h4>

<%= form_with scope: :log, model: @log, local: true do |form| %>
  <p>
    <%= form.label :title, 'Entry Title' %><br>
    <%= form.text_field :title, class: "title-text-field" %><br>
		<%= form.label :content, "Content - Great! Felt better?" %><br>
		<%= form.text_area :content, class: "log-text-area"%><br>
		<%= form.label :picture %><br>
		<%= cl_image_tag(@log.image, :width => 350, :fetch_format=>:auto, :crop=>"scale") %><br>
    <%= form.file_field :picture %><br>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Back', log_path, class: 'btn btn-primary' %>

app/views/logs/index.html.erb
<div class="jumbotron">
  <h1 class="display-4">Agenda</h1>
  <p class="lead">Keep your diary a secret</p>
  <hr class="my-4">
  <p>Yes. We mean it.</p>
  <p class="lead">
    <a
		class="btn btn-primary btn-lg"
		href="https://memegenerator.net/instance/45494779/catwoman-wisdom-everything-is-quantified-and-co-related"
		target="_blank"
		role="button">
			Learn more
		</a>
  </p><br/>

<h4>Agenda Entries</h4>
	<%= form_tag(logs_path, method: "get", remote: true) do %>
	<!-- if route comes back with JSON, page will not load unless it is html
	to read what remote true does.
	but next bit is to do fetch. can do fetch in publicly assessible API endpoints
	SWAPI, star wards API -->
		<%= text_field_tag :search, params[:search], placeholder: "Enter entry title" %>
		<%= submit_tag "Search" %>
	<% end %> <br/>

	<div class="container">
  	<div class="row">
			<div id = "log-table">

				<table class="table table-striped">

					<thead>
						<tr>
							<th scope="col">Title</th>
							<th scope="col">Created On</th>
							<th scope="col">Thumb Nails</th>
						</tr>
					</thead>
				<tbody>
					<% @logs.each do |log| %>
						<tr>
							<td class = "log-title"><%= log.title %></td>
							<td><%= log.created_at.strftime('%d.%m.%Y') %></td>
							<td> <%= cl_image_tag(log.image, :width => 50, :fetch_format=>:auto, :crop=>"scale")%></td>
							<td>
								<%= link_to 'Show', log_path(log)%>
							</td>
							<td>
								<%= link_to 'Edit', edit_log_path(log)%>
							</td>
							<td>
								<%= link_to 'Delete', log_path(log),
								method: :delete,
								data: { confirm: 'Are you really sure you want to delete this entry??' } %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
		<div id = "search-results"></div>
	</div>
</div>

<% if user_signed_in? %>
	<%= link_to 'Add New Log', new_log_path %>
<% end %>

<!--<img src = "<%= image_url 'bears-guts-raw-run.jpg' %>" class = "home-bottom-image"/> -->

app/views/logs/new.html.erb
<h4>Create New Entry</h4>

<%= form_with scope: :log, url: logs_path, local: true do |form| %>
  <p>
    <%= form.label :title, "Entry Title*"%><br>
    <%= form.text_field :title, class: "title-text-field" %><br>
		<%= form.label :content, "Content - How did you feel today?" %><br>
    <%= form.text_area :content, class: "log-text-area" %><br>
		<%= form.label :picture, "Picture (happy maybe?)*" %><br>
		<!--<%= cl_image_upload_tag(:picture, :html => { :multiple => false }) %> -->
    <%= form.file_field :picture %>
  </p>
    <%= form.submit "Save Entry" %>
<% end %> <br/>

<%= link_to 'Back', logs_path, class: 'btn btn-primary' %>

app/views/logs/show.html.erb
<h4> Entry Title: </h4>
<p>
  <%= @log.title %> <br/>
</p>

<h4> Content:</h4>
<p>
	<% if @log.content == nil %>
		<%= '' %>
	<% else %>
		<%= simple_format(@log.content) %>
	<% end %>
</p>

<%= link_to 'Back', logs_path, class: 'btn btn-primary' %> |
<%= link_to 'Edit',  edit_log_path, class: 'btn btn-secondary' %> <br/><br/>

<%= cl_image_tag(@log.image, :width => 350, :fetch_format=>:auto, :crop=>"scale") %> <br/>